// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feefiyeqczhynxniuqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZWZpeWVxY3poeW54bml1cXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTg1MTYsImV4cCI6MjA3MDU5NDUxNn0.OlNG1t8zhLAfwtyfkIWf39XNYhaFmcn3QHjyRUfvrAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});